# Generated by Django 5.2.7 on 2025-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
