# Generated by Django 5.2.7 on 2025-12-10 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entry_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['entry', 'created_at'], name='myapp_comme_entry_i_9c958c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='myapp_comme_author__58368c_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-created_at', 'author'], name='myapp_entry_created_9f85f6_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['category'], name='myapp_entry_categor_6fc707_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author'], name='myapp_entry_author__64cb58_idx'),
        ),
    ]
