# Generated by Django 5.2.7 on 2025-12-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment_myapp_comme_entry_i_9c958c_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
