# Generated by Django 5.2.7 on 2026-02-25 08:19

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_entry_like_count_entry_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('ST', 'Education'), ('LS', 'Lifestyle'), ('HE', 'Health & Wellness')], max_length=2),
        ),
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='myapp_entry_created_9f85f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='myapp_entry_categor_6fc707_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='myapp_entry_author__64cb58_idx',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='views',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['entry', 'is_published', 'created_at'], name='myapp_comme_entry_i_a71043_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'is_published'], name='myapp_comme_author__83ef3c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tree_id', 'lft'], name='myapp_comment_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_published', '-created_at'], name='myapp_entry_is_publ_e489ec_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'is_published'], name='myapp_entry_author__559abe_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['category', 'is_published'], name='myapp_entry_categor_763467_idx'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
